### ISSUE TITLE
Help needed choosing the correct PyU4V version

### ISSUE THREAD

**Issue by globeid-dev** [dell/PyU4V#103]
Hello, 
I've been using PyU4V==9.1.5.0 to connect to Unisphere ('V9.1.0.2', '91') for sometime and have been able to manage all operations just fine. 
However I'm now trying to connect to Unispehere ("version": "V8.4.0.27") and unable to do so. I was wondering if I need to step down to PyU4V ver#3.1.7. And, will it let me connect to unispehere: 91 if I do so.

Any help is appreciated.
Thanks

conn = PyU4V.univmax_conn.U4VConn(username='user', password='passed', server_ip='host', port='8443', verify=False, u4v_version='84')

**Comment by rawstorage** [comment]
You should use version 3.x for unisphere versions lower than 9.1 this is documented in the docs here https://pyu4v.readthedocs.io/en/latest/installation.html

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by helenwalsh** [comment]
Hi,
We only use the latest endpoint version since PyU4V 9.1.0.0 so U4P optimizations and bug fixes will be picked up by PyU4V.  
You are correct in that you must install earlier PyU4V versions for 84 endpoints, e.g. 3.1.7
https://pypi.org/project/PyU4V/#history
pip install pyu4v==3.1.7

While you can connect to Unisphere for PowerMax 91 with PyU4V 3.1.7, you are missing out on potential optimizations and bug fixes that would be available in PyU4V==9.1.5.0 as this version of PyU4V only supports legacy 84 and 90 endpoints.

Hopefully this helps
Kind regards,
Helen

**Comment by globeid-dev** [comment]
Thanks.
