### ISSUE TITLE
Help needed to understand Copy session Target device

### ISSUE THREAD

**Issue by guptamukeshkc** [dell/PyU4V#107]
Hello, 
We are using PyU4V= 9.1.3.0. with PowerMax.

Steps followed:
1. Create snapshot of a storage group with volumes.
2. Create and link the new storage group with the snapshot created.
3. Create masking view id and attach it to the host.

Now, while we were testing the above code in at scale, we observed that after the very first create and link of the storage with snapshot is completed.
we observe the following error traceback:

`ERROR - Request failed unexpectedly"
"Traceback (most recent call last):"
"  File ""/tmp/libs/powermax/lib/PyU4V/replication.py"", line 422, in modify_storage_group_snapshot"
"    return self.modify_resource("
"  File ""/tmp/libs/powermax/lib/PyU4V/common.py"", line 409, in modify_resource"
"    self.check_status_code_success(operation, status_code, message)"
"  File ""/tmp/libs/powermax/lib/PyU4V/common.py"", line 181, in check_status_code_success"
"    raise exception.VolumeBackendAPIException("
"PyU4V.utils.exception.VolumeBackendAPIException: Bad or unexpected response from the storage volume backend API: Error PUT symmetrix resource. The status code received is 500 and the message is {'message': 'A problem occurred modifying the snapshot generation resource: The Target device cannot be manipulated because it is already a Copy session Target device'}."`

So, the error message : **A problem occurred modifying the snapshot generation resource: The Target device cannot be manipulated because it is already a Copy session Target device'**

This occurs as soon as the first storage group is created and linked.
1. can you please point out to docs regarding different session and how to leverage it.
2. since the operation was in scale we maintained one session, do we need to terminate each session post every call.
3. Do we need to specify any wait or interval between operations any docuementations on that would also be helpful.
4. And lastly any scale numbers that are recommended for scale operations.

Anything else apart from the above that you want to suggest would be really  helpful.

**Comment by rawstorage** [comment]
Hi,
The problem appears to be that you are attempting to link a snapshot to a volume that is alrrady linked to a previous generation. In this case you should unlink or relink. You should be able to link again after unlink without any wait period.

The operations for snapvx operations are called out in the Solutions enabler documents.

This is not an issue with scale simply  the order in which you are doing things.

The following document should also help. One thing to consider is that the latest code release uses snapset id to identify snapshots rather than generation, this is much easier to work with at scale as the snapid doesn't change if another snapshot with the same name is created.  Details are also in the tech note

https://www.delltechnologies.com/resources/en-us/asset/white-papers/products/storage/h13697-dell-emc-powermax-vmax-all-flash-timefinder-snapvx-local-replication.pdf&ved=2ahUKEwia7b7yy7ztAhVKRBUIHUSLCvEQFjAAegQIAxAC&usg=AOvVaw17eMSOYtd2402nzfxBZ7dJ<https://www.google.com/url?sa=t&source=web&rct=j&url=https://www.delltechnologies.com/resources/en-us/asset/white-papers/products/storage/h13697-dell-emc-powermax-vmax-all-flash-timefinder-snapvx-local-replication.pdf&ved=2ahUKEwia7b7yy7ztAhVKRBUIHUSLCvEQFjAAegQIAxAC&usg=AOvVaw17eMSOYtd2402nzfxBZ7dJ>

Hope this helps.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
