### ISSUE TITLE
How to change SRDF Storage group state to partition state using symcli 10.x or Unisphere 9.2

### ISSUE THREAD

**Issue by vijayshihan** [dell/PyU4V#193]
How to change SRDF Storage group state to partition state using symcli 10.x or Unisphere 9.2

Please help as soon as

**Comment by rawstorage** [comment]
Partition state is not a normal state.  This is usually indicative of a problem.  Please review the solutions enabler srdf cli users guide rather than opening an issue for each query this is an open source project that requires specialist knowledge of the product, you should be able to consult with your storage team to fill knowledge gaps like this. It's not an issue with PyU4V.  Sorry to push back but there a lot of questions being opened that are product relates rather than issues with the PyU4V project.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>


Internal Use - Confidential

________________________________
From: vijayshihan ***@***.***>
Sent: Monday, July 8, 2024 2:10:08 PM
To: dell/PyU4V ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [dell/PyU4V] How to change SRDF Storage group state to partition state using symcli 10.x or Unisphere 9.2 (Issue #193)


[EXTERNAL EMAIL]

How to change SRDF Storage group state to partition state using symcli 10.x or Unisphere 9.2

Please help as soon as
