### ISSUE TITLE
Unable to import PyU4V

### ISSUE THREAD

**Issue by Kay-Kay83** [dell/PyU4V#20]
Hello,

I am a novice and hence the question. I am trying to import the PyU4V library and it errors out with a syntax error at the location with the statement

```
def create_host(self, host_name, initiator_list=None,
                    host_flags=None, init_file=None, async=False):

```
The error that I see is 

   ```
host_flags=None, init_file=None, async=False):
                                         ^
SyntaxError: invalid syntax

```
Is there a trick that I missing here?, I generally have been working on other API's and haven't seen such problems there.

I would appreciate any help with respect to this error.

Regards,
KayK

**Comment by ciarams87** [comment]
Hi KayK,

I don't think I'm exactly sure what your issue is. When you say you are trying to import the library, do you mean that the error is occurring when you use the import statement, i.e. 'import PyU4V'?, or when you try and call that particular function? If it is at the import stage, how did you install the library? 

It might help to refer to the documentation: http://pyu4v.readthedocs.io/en/latest/ 

Thanks,
Ciara

**Comment by edgaruribe369** [comment]
Salutations,

I am also having the same issue with Python3.7. I keep getting a SyntaxError:

**"......./PyU4V/provisioning.py", line 133
    host_flags=None, init_file=None, async=False):**
                                                                    ^
This happens promptly after my import line:

**from PyU4V import U4VConn**

I've installed everything as you have mentioned in your documentation :)

----EDIT-----

I'll note that it works with Python2.7

**Comment by ghost** [comment]
Hi Edgar,

PyU4V is built to run with Python 2.7 or 3.6 at present as dictated by the coverage of the Tox tests, if you downgrade your Python version to one of those two you should have no further issues.

Thanks
Michael
