### ISSUE TITLE
unisphere out of sync issue?

### ISSUE THREAD

**Issue by mallilinux1978** [dell/PyU4V#82]
Hi,

have you ever noticed unisphere DB going to out-of-sync? If answer is yes should i run any other API or CLI to make sure unisphere DB & symapi DB is 100% sync?

In our cause, we'll create devices using POST, and then query using GET unisphere for the device ids we just created, and unisphere will say the device id doesn't exist, even though it was just created. Currently we use unisphere version 8.3 and provisioning tool written in JAVA. I wish tool would have been in Python so can simply used PyU4V which could have taken care out-of-sync issue under the wood.

**Comment by rawstorage** [comment]
Hi, there were some significant improvements in the API since version 8.4 and 9.0/9.1, if you are creating the devices via REST and querying on the same instance of Unisphere you shouldn't expect to see any out of sync issue.  If you are querying separate instances of unipshere you may need to run a refresh within the GUI to sync this up.

**Comment by MichaelMcAleer** [comment]
Closing this one out - not PyU4V related or using most recent versions of Unisphere.
