### ISSUE TITLE
Embedded unisphere V9.1.0.15 error in function validate_unisphere

### ISSUE THREAD

**Issue by tgu4** [dell/PyU4V#90]
In common.py line 492 in get_uni_version, the return version is <class 'str'>, while with linux unisphere the return version is <class 'dict'>. The version_list = version['version'].split(',') will return TypeError: string indices must be integers

**Comment by MichaelMcAleer** [comment]
Hi There,

Following the guidelines in our documentation for issues ([link](https://pyu4v.readthedocs.io/en/latest/support.html)) can you provide some additional information on your environment? I'll need them to confirm we are both looking at the same code and versions of requirements.

I have looked at the function and associated response from Unisphere 9.1.0.15...

https://github.com/dell/PyU4V/blob/master/PyU4V/common.py#L482

```
    def get_uni_version(self):
        """Get the unisphere version from the server.
        :returns: version and major_version e.g. "V9.1.0.2", "91" -- str, str
        """
        version, major_version = None, None
        response = self.get_resource(category=VERSION, no_version=True)
        if response and response.get('version'):
            version = response['version']
            version_list = version.split('.')
            major_version = version_list[0][1] + version_list[1]
        return version, major_version
```

In the code block above Unisphere returns the following for `response = self.get_resource(category=VERSION, no_version=True)`:

`{"version": "V9.1.0.15"}`

Processing this response, and only doing so because there was a response and the `version` key was present, the version value is extracted from the response dict and the string split by `.` character.

Running this call I get the following returned:

`('V9.1.0.15', '91')`

Can you please confirm that you are seeing something different from what I outlined here, and if so include all the required details about your env as outlined in our guide for issues.

Thanks!
Michael

**Comment by tgu4** [comment]
hi Michael,

in the linux installed unisphere or directly use array service processes ip unisphere they returned correctly
{"version": "V9.1.0.15"}

now powermax has embedded management unisphere. We will use this for performance metrics collection so using in band HBA fabric on linux server can be eliminated. when use none modified PyU4V connect to that it will return 
('V9.1.0.15', '91')
as a result it return TypeError: string indices must be integers

details including the snippets of code and error on them were sent via internal email to Paul Martin, please check with him to see if he can forward you that.

**Comment by MichaelMcAleer** [comment]
Hi Tommy,

I checked embedded unisphere and it returns the same expected response from the rest API:

`{"version": "V9.1.0.15"}`

Is the problem that you are expecting to see this returned from `get_uni_version()` but instead you get returned `('V9.1.0.15', '91')`?

**Comment by tgu4** [comment]
Michael, check your email. just forward you the detail. Tommy

**Comment by MichaelMcAleer** [comment]
Hi Tommy,

Just had a look at the code snippet. 

Similar to Paul's response in issue https://github.com/dell/PyU4V/issues/89 can you please set Unisphere configuration setting `com.emc.em.restapi.WrapJsonRoot` to its default setting of `False` and try again?

PyU4V is developed to work out of the box, by setting WrapJsonRoot you are changing the Unisphere REST API response format which is going to impact most, if not all of the functions in PyU4V.

Thanks
Michael

**Comment by tgu4** [comment]
Michael, 

We did not change on embedded unisphere one so it should be default to False, and I don’t know how I can do it without Dell support help :) but I might changed your code somewhere for the debugging and forgot to change back. Let me check that later and let you know to confirm if that is the case.

Thanks, Tommy

**Comment by tgu4** [comment]
Michael, 

It appears I left the file changed after series debug to make it work. It looks good with embedded unisphere.  sorry for the confusion.

**Comment by MichaelMcAleer** [comment]
Hi Tommy, 

Thanks for the update and letting us know, if you need any more help with any PyU4V problems just open an issue and we will investigate.

Thanks
Michael
